### ISSUE TITLE
Add `EditorConfig.EditorConfig` and generate `.editorconfig` 

### ISSUE THREAD

**Issue by duodecanol** [duodecanol/pyenv-poetry-devcontainer#3]
## Preferable `.editorconfig` setting from the previous projects

```toml
root = true

[*]
tab_width = 4
end_of_line = lf
max_line_length = 88
ij_visual_guides = 88
insert_final_newline = true
trim_trailing_whitespace = true

[*.{js,py,html}]
charset = utf-8

[*.md]
trim_trailing_whitespace = false

[*.{yml,yaml}]
indent_style = space
indent_size = 2

[Makefile]
indent_style = tab

[.flake8]
indent_style = space
indent_size = 2

[*.json]
indent_style = space
indent_size = 2

[*.py]
indent_style = space
indent_size = 4
ij_python_from_import_parentheses_force_if_multiline = true
```
